data:extend{
    {
        type = "double-setting",
        name = "meltdown-player-pollution-damage-resistance",
        setting_type = "runtime-global",
        default_value = 100.0,
        maximum_value = 100.0,
        minimum_value = 0.0,
        order = "meltdown-player-pollution-damage-resistance",
    },
    {
        type = "double-setting",
        name = "meltdown-player-pollution-damage-reduction",
        setting_type = "runtime-global",
        default_value = 10.0,
        minimum_value = 0.0,
        order = "meltdown-player-pollution-damage-reduction",
    },
    {
        type = "bool-setting",
        name = "meltdown-prevent-mining",
        setting_type = "runtime-global",
        default_value = true,
        order = "meltdown-prevent-mining",
    },
    {
        type = "bool-setting",
        name = "meltdown-explode",
        setting_type = "runtime-global",
        default_value = false,
        order = "meltdown-explode",
    },
    {
        type = "double-setting",
        name = "meltdown-pollution",
        setting_type = "runtime-global",
        default_value = 1000000.0,
        minimum_value = 0.0,
        order = "meltdown-pollution",
    },
    {
        type = "double-setting",
        name = "meltdown-overheat-damage-per-second",
        setting_type = "runtime-global",
        default_value = 0.0,
        minimum_value = 0.0,
        order = "meltdown-overheat-damage-per-second",
    },
    {
        type = "double-setting",
        name = "meltdown-overheat-pollution-per-second",
        setting_type = "runtime-global",
        default_value = 10.0,
        minimum_value = 0.0,
        order = "meltdown-overheat-pollution-per-second",
    },
    {
        type = "double-setting",
        name = "meltdown-overheat-fires-per-second",
        setting_type = "runtime-global",
        default_value = 1.0,
        maximum_value = 60.0,
        minimum_value = 0.0,
        order = "meltdown-overheat-fires-per-second",
    },
}
